// GENERATED by scripts/blender/pack-strip.mjs -- do not edit by hand.
// Regenerate with:  node scripts/blender/pack-strip.mjs
//
// Describes the sprite sheets in client/public/sprites/. Columns are
// animation frames, rows are tileHash variants; every sheet is stored at
// 2x the logical size below. The anchor is always the centre of the
// logical box, because kit.py aims the camera at the world origin and models
// are built centred there.

export interface GeneratedStrip {
  /** Animation frames, laid out left to right. */
  frames: number;
  /** Deterministic variants, laid out top to bottom, picked by tileHash. */
  variants: number;
  /** Logical size in world px. */
  w: number;
  h: number;
  /** Footprint in map tiles (1 = 1x1, 2 = 2x2, ...). */
  tiles: number;
}

export const PACK_SCALE = 2;

export const STRIPS: Record<string, GeneratedStrip> = {
  balloonstand: { frames: 8, variants: 1, w: 96, h: 144, tiles: 1 },
  bench: { frames: 1, variants: 2, w: 96, h: 96, tiles: 1 },
  bumper: { frames: 16, variants: 1, w: 96, h: 112, tiles: 1 },
  carousel: { frames: 16, variants: 1, w: 96, h: 128, tiles: 1 },
  coaster: { frames: 12, variants: 1, w: 176, h: 176, tiles: 2 },
  drinkstall: { frames: 8, variants: 1, w: 96, h: 128, tiles: 1 },
  droptower: { frames: 16, variants: 1, w: 96, h: 208, tiles: 1 },
  ferriswheel: { frames: 12, variants: 1, w: 176, h: 272, tiles: 2 },
  flowerbed: { frames: 1, variants: 2, w: 96, h: 96, tiles: 1 },
  foodstall: { frames: 8, variants: 1, w: 96, h: 128, tiles: 1 },
  fountain: { frames: 8, variants: 1, w: 96, h: 112, tiles: 1 },
  gokarts: { frames: 12, variants: 1, w: 176, h: 144, tiles: 2 },
  haunted: { frames: 1, variants: 1, w: 176, h: 176, tiles: 2 },
  lamp: { frames: 1, variants: 1, w: 96, h: 128, tiles: 1 },
  megacoaster: { frames: 12, variants: 1, w: 320, h: 352, tiles: 4 },
  restroom: { frames: 1, variants: 1, w: 96, h: 112, tiles: 1 },
  ship: { frames: 16, variants: 1, w: 176, h: 208, tiles: 2 },
  teacups: { frames: 16, variants: 1, w: 96, h: 112, tiles: 1 },
  trashcan: { frames: 1, variants: 1, w: 96, h: 96, tiles: 1 },
  tree: { frames: 8, variants: 3, w: 96, h: 128, tiles: 1 },
};
